'use client'

import {
  Icon24SearchOutline as SearchIcon,
  Icon28Profile as ProfileIcon,
  Icon24NewsfeedOutline as NewsIcon,
  Icon24MessageOutline as MessengerIcon,
  Icon24PhoneOutline as CallsIcon,
  Icon24UsersOutline as FriendsIcon,
  Icon24Users3Outline as GroupsIcon,
  Icon24LogoVkMusicOutline as VKMusicIcon,
  Icon28LogoVkVideoOutline as VideoIcon,
  Icon24LogoVkColor as VKLogoIcon,
  Icon24GameOutline as GamesIcon,
  Icon24SmileOutline as StickersIcon,
  Icon24MarketOutline as MarketIcon,
  Icon24ServicesOutline as ServicesIcon,
  Icon24BookmarkOutline as FavoriteIcon,
  Icon24DocumentOutline as FilesIcon,
  Icon28Notifications as NotificationIcon,
  Icon24MusicOutline as MusicIcon,
  Icon12ChevronDownSmall as ChevronDownIcon,
  Icon24Fire as FireIcon,
  Icon16MoreHorizontal as HorizontalDotsMenuIcon,
  Icon24LikeOutline as LikeIcon,
  Icon24CommentOutline as CommentIcon,
  Icon24ShareOutline as ShareIcon,
  Icon24View as ViewsIcon,
} from '@vkontakte/icons/'

export {
  ProfileIcon,
  NewsIcon,
  MessengerIcon,
  CallsIcon,
  FriendsIcon,
  GroupsIcon,
  VKMusicIcon,
  VideoIcon,
  GamesIcon,
  StickersIcon,
  MarketIcon,
  ServicesIcon,
  FavoriteIcon,
  FilesIcon,
  VKLogoIcon,
  NotificationIcon,
  MusicIcon,
  ChevronDownIcon,
  SearchIcon,
  FireIcon,
  HorizontalDotsMenuIcon,
  LikeIcon,
  CommentIcon,
  ShareIcon,
  ViewsIcon,
}
